
export interface Property {
  id: string;
  hostId: string;
  title: string;
  description: string;
  pricePerNight: number;
  country: string;
  city: string;
  address: string;
  maxGuests: number;
  bedrooms: number;
  bathrooms: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// This interface represents the structure of a property record in the database, with snake_case field names to match typical SQL column naming conventions.
export interface PropertyRow {
  id: string;
  host_id: string;
  title: string;
  description: string;
  price_per_night: string;
  country: string;
  city: string;
  address: string;
  max_guests: number;
  bedrooms: number;
  bathrooms: number;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

// This interface is used for creating a new property, it doesn't include fields like id, createdAt, updatedAt which are generated by the system.
export interface CreatePropertyInput {
  title: string;
  description: string;

  pricePerNight: number;

  country: string;
  city: string;
  address: string;

  maxGuests: number;

  bedrooms: number;
  bathrooms: number;
}

// This interface represents the structure of a property response sent back to clients, it includes all relevant fields but may exclude sensitive information if needed.
export interface CreatePropertyData {
  hostId: string;
  title: string;
  description: string;
  pricePerNight: number;
  country: string;
  city: string;
  address: string;
  maxGuests: number;
  bedrooms: number;
  bathrooms: number;
}

// This interface represents the structure of a property response sent back to clients, it includes all relevant fields but may exclude sensitive information if needed.
export interface PropertyResponse {
  id: string;
  hostId: string;
  title: string;
  description: string;
  pricePerNight: number;
  country: string;
  city: string;
  address: string;
  maxGuests: number;
  bedrooms: number;
  bathrooms: number;
  createdAt: Date;
}

export const propertySortField = ["createdAt", "price"] as const;
export type PropertySortField = typeof propertySortField[number];

export const sortOrder = ["asc", "desc"] as const;
export type SortOrder = typeof sortOrder[number];

export interface PaginationOptions {
  page: number;
  limit: number;
  sortBy?: PropertySortField;
  sortOrder?: SortOrder;
}

export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}